#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "🖥 CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)\\n(100% per core)" ;;
	2) st -e htop;;
	3) notify-send "🖥 CPU module " "\- Shows 🌡 CPU temperature.
- Click to show intensive processes.
- Middle click to open htop." ;;
	6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

CPU_TEMP=($(sensors | awk '/Core 0/ {print $3 }' | sed "s/\+//" | cut -f1 -d"." | sed ':a;N;$!ba;s/\n/\//'))

RES="🌡CPU:$CPU_TEMP°C"
echo "$RES"
