#!/bin/sh

STATUS=$(cat $HOME/.cache/fans)

if [[ -z "$STATUS" ]]; then
    sudo isw -b off && echo 0 >$HOME/.cache/fans
    STATUS=$(cat $HOME/.cache/fans)
fi

toggle() {
    case "$STATUS" in
        0) sudo isw -b on && echo 1 >$HOME/.cache/fans ;;
        1) sudo isw -b off && echo 0 >$HOME/.cache/fans ;;
    esac
}

case $BLOCK_BUTTON in
    1) toggle ;;
    3) notify-send "💫 Fan booster module" "\- Click to toggle
🍀: Cooler Model OFF
🌀: Cooler Model ON
" ;;
    6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

case $STATUS in
    0) MODE="🍀OFF" ;;
    1) MODE="🌀ON" ;;
esac

RES="$MODE"
echo "$RES"
