#!/bin/sh

case $BLOCK_BUTTON in
    1) sudo dmenugpu ;;
    3) notify-send "🔰 GPU module" "\- Click to toggle
🚀: Nvidia
💻: Intel
" ;;
    6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

# GPU_TEMP=($(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader))
# if [[ $GPU_TEMP == *"NVIDIA-SMI"* ]]; then
#   RES="CPU:🌡$CPU_TEMP°C"
# else
#   RES="CPU:🌡$CPU_TEMP°C|GPU:🌡$GPU_TEMP°C"
# fi

case $GPU_MODE in
    intel) MODE="💻GPU:Intel" ;;
    nvidia)
        POWER=$(nvidia-smi --query-gpu=power.draw --format=csv,noheader,nounits)
        MODE="🚀GPU:Nvidia(${POWER%.*}W)"
        ;;
    hybrid) MODE="✨GPU:Hybrid" ;;
esac

RES="$MODE"
echo "$RES"
