#!/bin/sh

# Show wifi 📶 and percent strength or 📡 if none.
# Show 🌐 if connected to ethernet or ❎ if none.
# Show 🔒 if a vpn connection is active

case $BLOCK_BUTTON in
    1)
        iwd-dmenu
        pkill -RTMIN+4 dwmblocks
        ;;
		2) setsid -f "$TERMINAL" -e bluetuith ;;
    3) notify-send "🌎 Internet module" "\- Left click to connect
- Mid click opens bluetuith
❌: no network
📶: wifi connection with quality
🌎: ethernet working
" ;;
		6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

# Wifi
if [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = 'up' ]; then
    sigStr="$(awk '/^\s*w/ {print int($3 * 100 / 70) "%"}' /proc/net/wireless)"
    device="$(iwctl device list | awk 'FNR == 5 {print $2}')"
    # ssid="$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -c 5-)" # for networkmanager
    ssid="$(iwctl station $device show | grep 'Connected network' | awk '{print $3}')"
    wifiicon="📶$ssid($sigStr)"
fi

# Ethernet
grep -q 'up' /sys/class/net/e*/operstate 2>/dev/null && ethericon="🌎LAN"

# Clash
[ -n "$(cat /sys/class/net/utun*/operstate 2>/dev/null)" ] && tunicon="🔒"

[ -z "$wifiicon" ] && [ -z "$ethericon" ] && [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = 'down' ] && { ([ "$(cat /sys/class/net/w*/flags 2>/dev/null)" = '0x1003' ] && wifiicon="📡") || wifiicon="❌"; }

printf "%s%s%s\n" "$tunicon" "$wifiicon" "$ethericon"
